library/Controllers/AccountsController.cs
using AutoMapper;
using BusinessLayer.Services.BookService;
using BusinessLayer.Services.UserService;
using DAL.Entities;
using library.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace library.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IUserAppServices _userAppServices;

        private readonly IMapper _mapper;

        public AccountsController( IMapper mapper, IUserAppServices userAppServices)
        {
           
            _userAppServices = userAppServices;
            _mapper = mapper;
        }

        [AllowAnonymous]

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]

        public async Task<ActionResult> Login(CreateUserDTO model)
        {
            int id = await _userAppServices.logIn(model.UserName, model.Password);
            if (id>0) {
                FormsAuthentication.SetAuthCookie(model.UserName, false);
                return RedirectToAction("Index","Home");
            }

            else
            {
                TempData["msg"] = "Incorrect Username Or Password ";
                return View();
            }
         

        }


        public ActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult >Signup(CreateUserDTO model)
        {
            var UserEntity = _mapper.Map<User>(model);

            int id = await _userAppServices.CreateAsync(UserEntity);
            if (id>0) { 
            return RedirectToAction("Login");

            }
            TempData["msg"] = "Faild To insert User ";
            return View();
        }


     
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

    }
}

library/Controllers/BorrowController.cs
using AutoMapper;
using BusinessLayer.Services.BookService;
using DAL.Entities;
using library.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace library.Controllers
{
    [Authorize]
    public class BorrowController : Controller
    {
        private readonly IBookAppServices _bookAppServices;


        private readonly IMapper _mapper;

        public BorrowController(IBookAppServices bookAppServices, IMapper mapper)
        {
            _bookAppServices = bookAppServices;
            _mapper = mapper;

        }
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> Index(string Searchby, string search, int page = 1, int perPage =5)
        {
            IList<BookDTO> booksDto = new List<BookDTO>();
            IList<Book> books = new List<Book>();
            if (Searchby == "Title")
            {
                books = await _bookAppServices.ReadAsync(page, perPage, "Title", search);
                booksDto = _mapper.Map<List<BookDTO>>(books);
                return View(booksDto);

            }
            else if (Searchby == "Author")
            {
                books = await _bookAppServices.ReadAsync(page, perPage, "Author", search);
                booksDto = _mapper.Map<List<BookDTO>>(books);
                return View(booksDto);

            }
            else if (Searchby == "ISBN")
            {
                books = await _bookAppServices.ReadAsync(page, perPage, "ISBN", search);
                booksDto = _mapper.Map<List<BookDTO>>(books);
                return View(booksDto);

            }

            else
            {
                books = await _bookAppServices.ReadAsync(page, perPage, Searchby, search);
                booksDto = _mapper.Map<List<BookDTO>>(books);
            }

            return View(booksDto);
        }
        [HttpGet]
        [Authorize(Roles = ("Admin,User"))]
        public async Task<ActionResult> Borrow(int bookId, string username)
        {
           
            var id = await _bookAppServices.BorrowAnBookAsync(bookId,username);
            if (id != 0)
            {
                ViewBag.Messsage = "Book Borrwed Successfully";
            }
                return RedirectToAction("Index");
            
        }


        //[Authorize(Roles = ("Admin,User"))]
        //[HttpPost]

        //public async Task<ActionResult> Borrow()
        //{


        //    return View();


        //}

        [HttpGet]
        [Authorize(Roles = ("Admin,User"))]
        public async Task<ActionResult> Return(int bookId)
        {

            var id = await _bookAppServices.ReturnBookAsync(bookId);
            if (id != false)
            {
                ViewBag.Messsage = "Book Returned Successfully";
            }
            return RedirectToAction("Index");

        }
    }
}

library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Book Store</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="h-100 ">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Book Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1 justify-content-end">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        if (User.IsInRole("Admin") || User.IsInRole("User"))
                        {
                            <li>@Html.ActionLink("Store", "Index", "Borrow", new { area = "" }, new { @class = "nav-link" })</li>

                        }

                        if (User.IsInRole("Admin")) 
                        {
                            <li>@Html.ActionLink("Book", "Index", "Book", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("User", "Index", "User", new { area = "" }, new { @class = "nav-link" })</li>

                        }


                        <li>@Html.ActionLink("Logout", "Logout", "Accounts", new { area = "" }, new { @class = "nav-link" })</li>


                    }


                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content  ">
        @RenderBody()
        <hr />
        <footer   >
            <p>&copy; @DateTime.Now.Year -Book Store </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>